### ISSUE TITLE
0.2.5 breaks scalars with block notation

### ISSUE THREAD

**Issue by tenderlove** [yaml/libyaml#196]
Hi,

Version 0.2.5 seems to break scalars that use block notation but with custom tags.  For example:

```
---
hmm: !example.com,2002/type |
  hello
```

The above document would parse on 0.2.4, but 0.2.5 raises an exception:

```
did not find expected whitespace or line break while scanning a tag at line 2 column 6
```

Strangely, the following two documents both work on 0.2.4 as well as 0.2.5:

```
---
hmm: |
  hello
```

```
---
hmm: !binary |
  hello
```

I bisected and found that this was introduced in #179.  Before #179, all three of the above documents would successfully parse.

I can't tell if this is intentional, so I'm not 100% sure how to fix tests.  The tests in [Psych](https://github.com/ruby/psych) are failing with 0.2.5 but not 0.2.4.  Some of the failures are obvious problems in Psych's test suite, but this one isn't so obvious.

Thanks!

**Comment by perlpunk** [comment]
The comma is invalid in tags, so that is an intended change.
https://yaml.org/spec/1.2/spec.html#c-ns-shorthand-tag
https://yaml.org/spec/1.2/spec.html#ns-tag-char
```
[40] | ns-tag-char | ::= | ns-uri-char - “!” - c-flow-indicator
```
And flow-indicator contains the comma:
https://yaml.org/spec/1.2/spec.html#c-flow-indicator

So, commas are only allowed in tag handles or inside of `<>`:
```
!<tag:clarkevans.com,2002:invoice>
%TAG !yaml! tag:yaml.org,2002:
```
Sorry if it's breaking a use case.

I know that many libraries allow it, mostly because they were ported from libyaml.
The reference parser and yaml-cpp also don't accept the comma.

The use case for the fix was this testcase:
https://github.com/yaml/yaml-test-suite/blob/master/test/WZ62.tml
```
{
  foo : !!str,
  !!str : bar,
}
```
libyaml thought that the comma is part of the tag, and then the input is invalid.

I didn't actually expect people using commas in local tags...

**Comment by tenderlove** [comment]
> The comma is invalid in tags, so that is an intended change.

Cool



> I didn't actually expect people using commas in local tags...

TBH I don't know if anyone actually is.  These tests were ported from Syck as part of its implementation suite, so I don't think they say anything about real world usage.  I'll remove the commas from the suite in Psych.

Thanks for the quick response!

**Comment by perlpunk** [comment]
I did some more research. In YAML 1.1, the comma is indeed allowed:
```

[44] | ns-tag-char | ::= | ns-uri-char - “!”
```

I guess there was a areason for changing it in 1.2.

The correct thing would be to parse it depending on the YAML version, but currently there is
no handling of the version (and also no default version setting) in libyaml.

I guess @ingydotnet would have to decide what to do in this case.
Many libyaml based libraries are/were allowing this, so people out there might be relying on it.

**Comment by IPv2** [comment]
Thanks @perlpunk for this investigation, and to all of the libyaml contributors.

I confirm that Sup has been relying on this: we have used YAML tag `!supmua.org,2006-10-01/Redwood/Maildir` for years. (Issue https://github.com/sup-heliotrope/sup/issues/577 - credit to @krerkkiat for identifying this.)

We're intending to modify Sup to be YAML 1.2 compliant, but adding this comment in case you wanted a real-world example of a project that depended on the YAML 1.1 behaviour.
