### ISSUE TITLE
how to use with visual studio 2015?

### ISSUE THREAD

**Issue by mgiaco** [yaml/libyaml#54]
Hello,

I tried to use libyaml with visual studio 2015 community for a C project. I downloaded version 0.1.7 and build it with cmake and visual studio. So without any additional changes the build works fine i think. I get a yaml.lib in my output. After that I tried to use the yaml.lib in my project. I integrated the static lib but I get these errors.

```error
1>OLDNAMES.lib(strdup.obi) : error LNK2001: unresolved external symbol __imp__strdup
1>OLDNAMES.lib(strdup.obi) : error LNK2001: unresolved external symbol __imp___strdup
1>MSVCRTD.lib(_chandler4gs_.obj) : error LNK2019: unresolved external symbol __except_handler4_common referenced in function __except_handler4
```

Do I need any additional defines for building the lib? Or do I need any in my project where I would like to use the lib? I did not found any information in the web about building and using i this way for windows 7.

I also checked the platform toolset so did not find any solution...

many thanks

**Comment by sigmavirus24** [comment]
I have no experience with Visual Studio 2015 or any `yaml.lib` that it produces. I googled a little bit, though, and found that LNK2001 happens when you compile the two things differently. Here's some info for you: https://msdn.microsoft.com/en-us/library/f6xx1b1z.aspx https://social.msdn.microsoft.com/Forums/vstudio/en-US/d97b4ef8-621c-4b57-919a-9cfad482b39c/vs-2015-rc-emitting-lnk2001-errors-for-c-library-function-names?forum=vcgeneral https://msdn.microsoft.com/en-us/library/799kze2z.aspx

**Comment by mgiaco** [comment]
Many thanks i found the solution.

**Comment by sigmavirus24** [comment]
@mgiaco care to elaborate for other folks who may run into this issue?

**Comment by mgiaco** [comment]
I used cmake and vs2015 to build libyaml. So I found out that cmake enables /MD for the runtime. My problem was that Multi-threaded Debug (/MTd) was not enabled in my project. I do not exactly know why libyaml needs that but I changed it in my project without any issue.

I found the hint here [hint](https://www.gamedev.net/topic/343520-__imp__strdup/) and 
[some more information is here](https://msdn.microsoft.com/en-us/library/aa278396(v=vs.60).aspx)

Maybe this isn´t any problem for a every day windows and vs user ....
cheers
